
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: creating a security group firewall for the ec2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: AWS::EC2:Instance
    DependsOn: SecurityGroup
    Properties:
      SecurityGroups:
        - Ref: SecurityGroup
      KeyName: CJ
      ImageId: ami-052efd3df9dad4825
      InstanceType: t2.micro


