# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1

commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy the infrastructures
          command: | 
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}
          when: on_fail          
jobs:
  create-infrastructure:
    docker: 
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install tar utility
          command: |
            yum install -y tar gzip
      - run:
          name: Create Cloudformation stack
          command:  ./cf.sh template.yml myStack-${CIRCLE_WORKFLOW_ID:0:5} us-east-1
      
      - run:
          name: Update inventory file
          command: |
            echo '[all]' > inventory-2
            aws --region us-east-1 ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --filters "Name=tag:Project,Values=udacity" \
            --output text >> inventory-2
      - persist_to_workspace:
          root: ./
          paths:
            - inventory-2
  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.16
    
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["54:77:b2:48:a9:bf:01:c7:16:fe:9b:09:69:77:6a:5c"]
      - attach_workspace:
          at: ./
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run playbook and configure server
          command: |
            ansible-playbook main-remote.yml -i ./inventory-2
  create_and_deploy_frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Execute bucket.yml to create an s3 bucket
          command: |
            aws cloudformation deploy --stack-name stack-create-bucket-${CIRCLE_WORKFLOW_ID:0:7} --template-file bucket.yml --parameter-overrides BucketName=bucket-${CIRCLE_WORKFLOW_ID:0:7}
      - run: aws s3 sync . s3://bucket-${CIRCLE_WORKFLOW_ID:0:7} --delete
  get_last_deployment_id:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install -y tar gzip
      - run: 
          name: fetch and save old pipelines id bucket name responsible for last deployment
          command: |
            aws cloudformation \
            list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
            --no-paginate --output text > ~/textfile.txt
      - persist_to_workspace:
          root: ~/
          paths: 
            - textfile.txt
  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Execute cloudfront.yml
          command: |
            aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID=bucket-${CIRCLE_WORKFLOW_ID:0:7}
  clean_up_old_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install -y tar gzip
      - attach_workspace:
          at: ~/
      - run: 
          name: Destroy the previous s3 bucket and cloudformation stack
          command: |
            export OLDBUCKETID=$(cat ~/textfile.txt}
            aws s3 rm "s3://${OLDBUCKETID}" --recursive
  smoke_test:
    docker:
      - image: amazon/aws-cli 
    steps:
      - run: apk add --update curl
      - run: 
          name: smoke test
          command: |
            URL="https://blog.udacit673737y.com/"

            if curl -s --head $URL
            then
              return 0 
            else
              return 1 
            fi
      - destroy_environment

workflows:
  Infrastructure:
    jobs:
      - create_and_deploy_frontend
      - get_last_deployment_id
      - promote_to_production:
          requires:
            - create_and_deploy_frontend
      - clean_up_old_front_end: 
          requires:
            - get_last_deployment_id
            - promote_to_production
              
      # - create-infrastructure
        # - configure-infrastructure:
        # requires:
            # - create-infrastructure
            #- smoke_test:
            #requires:
            #- create-infrastructure
